# Generated by Django 3.2.3 on 2021-09-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210907_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Ordem', 'verbose_name_plural': 'Ordens'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ManyToManyField(blank=True, related_name='sale', to='dashboard.Product'),
        ),
    ]
