# Generated by Django 3.2.3 on 2021-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210908_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descição 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description_2',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descição 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_code',
            field=models.IntegerField(blank=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_code',
            field=models.IntegerField(verbose_name='Código de Referência'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponivel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_code',
            field=models.IntegerField(verbose_name='Código de Referência'),
        ),
    ]
