# Generated by Django 3.2.3 on 2021-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210908_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='internal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Interno'),
        ),
    ]
