# Generated by Django 3.2.3 on 2021-09-09 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_alter_order_internal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.IntegerField(verbose_name='Código de Referência')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Desconto')),
                ('nfe', models.BooleanField(default=False, verbose_name='Nota Fiscal Eletronica')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendas',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='dashboard.sale'),
        ),
    ]
