# Generated by Django 3.2.3 on 2021-09-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210909_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='dashboard.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='dashboard.Category'),
        ),
    ]
