# Generated by Django 3.2.3 on 2021-09-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Desconto'),
        ),
    ]
