# Generated by Django 3.2.3 on 2021-09-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210911_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitens',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens da Venda'},
        ),
    ]
