# Generated by Django 3.2.3 on 2021-09-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_saleitens_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='saleitens',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitens',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItens',
        ),
    ]
