# Generated by Django 3.2.3 on 2021-10-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_weight'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleItens',
            new_name='SaleItem',
        ),
    ]
