# Generated by Django 3.2.3 on 2021-09-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('nfe_change', 'Usuário pode alterar parâmetro NF-e'),), 'verbose_name': 'Vendas', 'verbose_name_plural': 'Vendas'},
        ),
    ]
