# Generated by Django 3.2.3 on 2021-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
