# Generated by Django 3.2.3 on 2021-09-19 20:13

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='customer', unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='reference_code', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
